Repository anacarolcortez/tech-challenge-fiap-parte1, pull requests merged in 2025-04, with the labels that each got.

#23 criando a pasta entities com a classe users e enum role
  ms-users/mvnw
  ms-users/pom.xml
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/MsUsersApplication.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/entities/Address.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/entities/Role.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/entities/Users.java
  ms-users/src/test/java/com/fiap/tech_challenge/parte1/ms_users/MsUsersApplicationTests.java
Labels: entity creation

#24 feat: implement DB migration structure and enhance Docker setup
  ms-users/.env.example
  ms-users/.gitignore
  ms-users/DOCKER_GUIDE.md
  ms-users/Dockerfile
  ms-users/docker-compose.yml
  ms-users/pom.xml
  ms-users/src/main/resources/application.yml
  ms-users/src/main/resources/db/migration/V1__init.sql
Labels: documentation, enhancement

#25 feat: initial create user structure
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/controllers/UsersController.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/dtos/UsersRequestDTO.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/repositories/UsersRepository.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/services/UsersService.java
Labels: users-endpoints

#29 criação do método findAllUsers(busca paginada)
  Repository
  ms-users/guides/postman_collection/importar.png
  ms-users/guides/postman_collection/ms-users.postman_collection.json
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/UserMapper.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/controllers/UsersController.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/repositories/UsersRepository.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/repositories/UsersRepositoryImpl.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/services/UsersService.java
Labels: users-endpoints

#32 Feature/get user by
  ms-users/local-continuous-integration.sh
  ms-users/pom.xml
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/UserMapper.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/controllers/UsersController.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/dtos/AddressRequestDTO.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/dtos/AddressResponseDTO.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/dtos/UsersRequestDTO.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/dtos/UsersResponseDTO.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/entities/Address.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/entities/Users.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/exceptions/DuplicatedAddressException.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/exceptions/EmailAlreadyExistsException.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/exceptions/GlobalExceptionHandler.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/exceptions/LoginAlreadyExistsException.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/mappers/AddressMapper.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/mappers/UserMapper.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/repositories/AddressesRepository.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/repositories/AddressesRepositoryImpl.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/repositories/UsersRepository.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/repositories/UsersRepositoryImpl.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/services/AddressesService.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/services/UsersService.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/services/validation/UsersValidationService.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/validators/DuplicatedAddressValidator.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/validators/EmailValidator.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/validators/LoginValidator.java
  ms-users/src/main/java/com/fiap/tech_challenge/parte1/ms_users/validators/UserValidator.java
  ms-users/src/main/resources/db/migration/V4__change_user_address_relation_to_one_to_many.sql
  ms-users/src/main/resources/db/migration/V5__add_on_delete_cascade_to_address_user_id_fk.sql
  ms-users/src/test/java/com/fiap/tech_challenge/parte1/ms_users/services/UsersServiceTest.java
Labels: enhancement
